name: deploy site

on:
  push:
    branches:
      - main
  schedule:
    # Run every 20 minutes
    - cron: "*/20 * * * *"

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: build the site
        run: |
          npm ci
          npm run build

      - uses: actions/checkout@v5
        with:
          ref: pages

      - run: mv docs/* .

