name: deploy site

on:
  push:
    branches:
      - main
  schedule:
    # Run every 20 minutes
    - cron: "*/20 * * * *"

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: build the site
        run: |
          npm ci
          npm run build

      - name: move the built artifacts
        run: |
          git fetch --unshallow origin pages
          git checkout pages
          mv docs/* .

      - name: check for changes
        id: diff
        run: if git diff --exit-code --quiet; then echo "has_changes=no" >> $FORGEJO_OUTPUT; else echo "has_changes=yes" >> $FORGEJO_OUTPUT; fi

      - name: commit if changes
        if: ${{ steps.diff.outputs.has_changes == 'yes' }}
        run: |
          git commit -am "update"
          git push

