name: deploy site

on:
  push:
    branches:
      - main
  schedule:
    # Run every hour
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: build the site
        run: |
          npm ci
          npm run build

      - name: move the built artifacts
        run: |
          git checkout pages
          mv docs/* .

      - name: check for changes
        id: diff
        run: if git diff --exit-code --quiet; then echo "has_changes=no" >> $GITHUB_OUTPUT; else echo "has_changes=yes" >> $GITHUB_OUTPUT; fi

      - name: commit if changes
        if: ${{ steps.diff.outputs.has_changes == 'yes' }}
        run: |
          git config user.name "Automatic update"
          git config user.email "git@greg.email"
          git commit -am "update"
          git push
